version: '3'

services:
  data_pipe_es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: data_pipe_es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
