#!/bin/bash

host=http://localhost:9200

curl -k -XDELETE --silent "$host/data_pipe,backup?pretty"

curl -k -XPUT --silent "$host/data_pipe?pretty" --header 'Content-Type: application/json' --data '
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1
  },
  "mappings": {
    "data": {
      "properties" : {
        "one" : {
          "type" : "keyword"
        },
        "two" : {
          "type" : "text"
        },
        "three" : {
          "type" : "integer"
        },
        "four" : {
          "type" : "date",
          "format" : "yyyy-MM-dd HH:mm:ss"
        }
      }
    }
  }
}
'

curl -k -XPUT --silent "$host/backup?pretty" --header 'Content-Type: application/json' --data '
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1
  },
  "mappings": {
    "data": {
      "properties" : {
        "five" : {
          "type" : "keyword"
        },
        "six" : {
          "type" : "text"
        },
        "seven" : {
          "type" : "integer"
        },
        "eight" : {
          "type" : "date",
          "format" : "yyyy-MM-dd HH:mm:ss"
        }
      }
    }
  }
}
'

curl -X POST --silent "$host/data_pipe/data?pretty" --header "Content-Type: application/json" --data '
{
	"one": "data_pipe",
	"two": "data pipe",
	"three": 42,
	"four": "2018-08-24 21:41:22"
}
'
